# Generated by Django 3.1 on 2021-03-16 20:49

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=100)),
                ('Technology_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=100)),
                ('Url', models.CharField(blank=True, max_length=100)),
                ('Contact_Name', models.CharField(blank=True, max_length=100)),
                ('First_Name', models.CharField(blank=True, max_length=100)),
                ('Last_Name', models.CharField(blank=True, max_length=100)),
                ('Contact_Title', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('State', models.CharField(blank=True, max_length=100)),
                ('Zip', models.CharField(blank=True, max_length=100)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('Fax', models.CharField(blank=True, max_length=100)),
                ('Total_Employees', models.CharField(blank=True, max_length=50)),
                ('Industry_Type', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
