# Generated by Django 3.1 on 2021-03-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='Technology_Type',
            field=models.CharField(blank=True, default='NaN', max_length=100, null=True),
        ),
    ]
